import re

# Read the test output from the console above
log_text = """2025-10-14 21:17:42,719 - scrapers.police_scraper - INFO - Police scraper summary: 2 incidents from 36/36 sources
2025-10-14 21:17:53,106 - scrapers.news_scraper - INFO - News scraper summary: 0 incidents from 36/36 sources
2025-10-14 21:18:04,971 - scrapers.twitter_scraper - INFO - Total incidents from Twitter: 0"""

print("=== SCRAPING SUMMARY ===\n")
print("Police sources: 36/36 active")
print("  - Found: 2 incidents")
print("  - Swedish (Stockholm): 1 incident ✓")
print("  - Danish (Copenhagen): 1 incident ✓")
print()
print("News sources: 36/36 active")
print("  - Found: 0 incidents")
print("  - All European feeds checked (BE, ES, IT, PL, AT, CH, DE, FR, GB)")
print()
print("Twitter sources: 10 active")
print("  - Found: 0 incidents")
print()
print("TOTAL: 2 incidents found and processed")
print()
print("=== EUROPEAN SOURCES STATUS ===")
print("✓ The Local Spain: RSS fetched successfully")
print("✓ The Local Italy: RSS fetched successfully")
print("✓ ANSA English: RSS fetched successfully")
print("✓ Notes From Poland: RSS fetched successfully")
print("✓ The Local Austria: RSS fetched successfully")
print("✓ The Local Switzerland: RSS fetched successfully")
print("✓ The Local Germany: RSS fetched successfully")
print("✓ France24: RSS fetched successfully")
print("✓ BBC UK News: RSS fetched successfully")
print()
print("⚠ Belgium drone plot article found but SKIPPED (no location extracted)")
print("  - Article: 'Belgium says it foiled suspected drone plot to attack prime ...'")
print("  - Reason: AI location extraction failed (401 auth error with dummy key)")
print()
print("=== KEY FINDINGS ===")
print("1. European RSS feeds ARE being scraped successfully")
print("2. All 36 news sources (including European) are active")
print("3. No drone incidents found in European feeds today")
print("4. Location extraction requires valid OpenRouter API key")
print("5. Geographic filtering is NOT blocking European articles")
